export const spacesData = [
  {
    id: 8,
    categories: ["Commercial", "Office"],
    image: "/spotlight/spotlight-img-1.jpg",
    date: "November 05, 2020",
    name: "Apex Tower",
    location: "USA, New York",
    clientImage: "/spaces/sarah-connor.png",
    clientName: "Sarah Connor",
    route: "/sample-space",
  },
  {
    id: 9,
    categories: ["Residential", "Loft"],
    image: "/spotlight/spotlight-img-2.jpg",
    date: "October 20, 2020",
    name: "Urban Loft",
    location: "UK, London",
    clientImage: "/spaces/profile-male-1.png",
    clientName: "Marcus Thorne",
    route: "/sample-space",
  },
  {
    id: 10,
    categories: ["Hospitality", "Hotel"],
    image: "/spotlight/spotlight-img-3.jpg",
    date: "September 15, 2020",
    name: "Azure Resort",
    location: "Maldives, Male",
    clientImage: "/spaces/profile-female-1.png",
    clientName: "Elena Vance",
    route: "/sample-space",
  },
  {
    id: 11,
    categories: ["Commercial", "Retail"],
    image: "/spotlight/spotlight-img-4.jpg",
    date: "August 10, 2020",
    name: "Vogue Boutique",
    location: "France, Paris",
    clientImage: "/spaces/profile-female-2.png",
    clientName: "Amélie Dubois",
    route: "/sample-space",
  },
  {
    id: 12,
    categories: ["Residential", "Villa"],
    image: "/spotlight/spotlight-img-5.jpg",
    date: "July 25, 2020",
    name: "Tuscan Villa",
    location: "Italy, Florence",
    clientImage: "/spaces/profile-male-2.png",
    clientName: "Luca Moretti",
    route: "/sample-space",
  },
  {
    id: 13,
    categories: ["Hospitality", "Restaurant"],
    image: "/spotlight/spotlight-img-6.jpg",
    date: "June 30, 2020",
    name: "Savor Bistro",
    location: "Spain, Barcelona",
    clientImage: "/spaces/profile-female-3.png",
    clientName: "Sofia Garcia",
    route: "/sample-space",
  },
  {
    id: 14,
    categories: ["Commercial", "Workspace"],
    image: "/spotlight/spotlight-img-7.jpg",
    date: "May 18, 2020",
    name: "Innovation Hub",
    location: "Germany, Berlin",
    clientImage: "/spaces/profile-male-3.png",
    clientName: "Klaus Weber",
    route: "/sample-space",
  },
  {
    id: 15,
    categories: ["Residential", "Apartment"],
    image: "/spotlight/spotlight-img-8.jpg",
    date: "April 05, 2020",
    name: "Skyline Apartment",
    location: "Canada, Toronto",
    clientImage: "/spaces/profile-male-1.png",
    clientName: "David Miller",
    route: "/sample-space",
  },
  {
    id: 16,
    categories: ["Hospitality", "Lounge"],
    image: "/spotlight/spotlight-img-9.jpg",
    date: "March 22, 2020",
    name: "Velvet Lounge",
    location: "USA, Los Angeles",
    clientImage: "/spaces/profile-female-1.png",
    clientName: "Jessica Doe",
    route: "/sample-space",
  },
  {
    id: 17,
    categories: ["Commercial", "Showroom"],
    image: "/spotlight/spotlight-img-10.jpg",
    date: "February 14, 2020",
    name: "Tech Showroom",
    location: "Japan, Tokyo",
    clientImage: "/spaces/profile-male-2.png",
    clientName: "Kenji Sato",
    route: "/sample-space",
  },
  {
    id: 18,
    categories: ["Residential", "Cottage"],
    image: "/featured-projects/featured-work-1.jpg",
    date: "January 08, 2020",
    name: "Cozy Cottage",
    location: "UK, Cotswolds",
    clientImage: "/spaces/profile-female-2.png",
    clientName: "Eleanor Brooks",
    route: "/sample-space",
  },
  {
    id: 19,
    categories: ["Hospitality", "Resort"],
    image: "/featured-projects/featured-work-2.jpg",
    date: "December 20, 2019",
    name: "Tropical Paradise",
    location: "Thailand, Phuket",
    clientImage: "/spaces/profile-male-3.png",
    clientName: "Arun Kitsana",
    route: "/sample-space",
  },
  {
    id: 20,
    categories: ["Commercial", "Office"],
    image: "/featured-projects/featured-work-3.jpg",
    date: "November 12, 2019",
    name: "Creative Office",
    location: "Sweden, Stockholm",
    clientImage: "/spaces/profile-male-1.png",
    clientName: "Lars Jensen",
    route: "/sample-space",
  },
];
